const points={display:{code:"01 / VISUAL CANVAS",title:"Interactive display",description:"A high-clarity teaching surface for content, annotation and shared ideas.",features:["Teachmint X interactive display","4K visual clarity","Precision multi-touch"]},camera:{code:"02 / PRESENCE",title:"Intelligent camera",description:"Automatic framing and high-quality video that connects every participant.",features:["4K camera","Intelligent framing","Hybrid learning ready"]},audio:{code:"03 / ROOM AUDIO",title:"Invisible intelligence",description:"Ceiling audio and microphone coverage designed around the room, not the device.",features:["Room-wide voice capture","Clear reinforcement","Conferencing integration"]},control:{code:"04 / CONTROL",title:"One room experience",description:"Simple control, device monitoring and secure access across the technology environment.",features:["Connected device health","NFC access","Central management"]},boardDisplay:{code:"01 / TEACHMINT",title:"Teachmint meeting display",description:"The room’s collaborative visual canvas for wireless sharing, interactive whiteboarding and clearer decision-making.",features:["Interactive whiteboard","Wireless screen sharing","Cloud meeting workflow"]},rallyBar:{code:"02 / LOGITECH",title:"Logitech Rally Bar",description:"An all-in-one video bar delivering professional camera, speaker and microphone performance for the boardroom.",features:["AI-powered video","Integrated room audio","Automatic framing"]},sight:{code:"03 / LOGITECH",title:"Logitech Sight",description:"A tabletop companion camera that gives remote participants a clearer view of people around the table.",features:["Table-level perspective","Multi-participant framing","Rally Bar integration"]},tap:{code:"04 / LOGITECH",title:"Logitech Tap",description:"A dedicated meeting-room touch controller for joining calls, sharing content and managing the room.",features:["One-touch join","Calendar integration","Clean cable management"]}};
const twin=document.querySelector(".twin"),images=[...document.querySelectorAll(".room-image")],card=document.querySelector(".point-card"),roomSlides=[...document.querySelectorAll(".room-slide")];
let activeRoom=0;
const roomMeta=[{label:"AUDITORIUM",kicker:"CONNECTED AUDITORIUM / 01"},{label:"BOARDROOM",kicker:"EXECUTIVE BOARDROOM / 02"}];
function showRoom(index){activeRoom=(index+roomSlides.length)%roomSlides.length;roomSlides.forEach((slide,i)=>slide.classList.toggle("active",i===activeRoom));document.querySelector(".room-nav strong").textContent=`0${activeRoom+1}`;document.querySelector(".room-nav small").textContent=roomMeta[activeRoom].label;document.querySelector(".twin-title p").textContent=roomMeta[activeRoom].kicker;card.hidden=true;tone("shift")}
document.querySelector(".room-next").onclick=()=>showRoom(activeRoom+1);document.querySelector(".room-prev").onclick=()=>showRoom(activeRoom-1);
document.querySelectorAll(".view-toggle button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".view-toggle button").forEach(x=>x.classList.toggle("active",x===b));twin.classList.toggle("digital",b.dataset.view==="digital");tone("shift")});
document.querySelectorAll(".hotspot").forEach(h=>h.onclick=()=>{const p=points[h.dataset.point];card.querySelector(".point-code").textContent=p.code;card.querySelector("h2").textContent=p.title;card.querySelector("p").textContent=p.description;card.querySelector("ul").innerHTML=p.features.map(x=>`<li>${x}</li>`).join("");card.hidden=false;tone("shift")});document.querySelector(".point-close").onclick=()=>card.hidden=true;
twin.addEventListener("pointermove",e=>{images.forEach(image=>{image.style.setProperty("--room-x",`${(e.clientX/innerWidth-.5)*-8}px`);image.style.setProperty("--room-y",`${(e.clientY/innerHeight-.5)*-5}px`)})});
let ctx,sound=true;const toggle=document.querySelector(".sound-toggle");function unlock(e){if(e.target.closest(".sound-toggle"))return;ctx=new(window.AudioContext||window.webkitAudioContext)();document.removeEventListener("pointerdown",unlock,true)}document.addEventListener("pointerdown",unlock,true);function tone(type="tap"){if(!sound||!ctx)return;const n=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),f=type==="shift"?[180,560,.17]:[230,115,.08];o.type=type==="shift"?"sine":"triangle";o.frequency.setValueAtTime(f[0],n);o.frequency.exponentialRampToValueAtTime(f[1],n+f[2]);g.gain.setValueAtTime(.03,n);g.gain.exponentialRampToValueAtTime(.0001,n+f[2]);o.connect(g).connect(ctx.destination);o.start();o.stop(n+f[2])}toggle.onclick=()=>{if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();sound=!sound;toggle.setAttribute("aria-pressed",sound);toggle.querySelector("span").textContent=sound?"Sound on":"Sound off";if(sound)tone("shift")};document.querySelectorAll(".sound-target").forEach(x=>{if(x!==toggle)x.addEventListener("click",()=>tone("tap"))});
