const products={
  neo:{code:"TM / X2N / 75",title:"Teachmint X2 Neo 75",description:"A flagship AI-powered connected classroom device combining a True 4K display, precision multi-touch, camera, microphone array and EduAI.",features:["EduAI teaching assistant","40-point multi-touch","4K camera and microphone array","Connected classroom software"]},
  star:{code:"TM / X2S / 75",title:"Teachmint X2 Star 75",description:"A streamlined interactive classroom display made for reliable everyday teaching, collaborative whiteboarding and effortless content sharing.",features:["Interactive 4K display","Teachmint Whiteboard","Wireless screen sharing","Cloud-ready classroom"]},
  vision:{code:"TM / VSNX",title:"Teachmint VisionX",description:"Secure classroom intelligence that gives administrators real-time visibility across connected learning spaces.",features:["Live classroom visibility","Screen and audio access","Broadcast alerts and logs","Privacy-first administration"]}
};
const cards=[...document.querySelectorAll(".lab-card")],track=document.querySelector(".cards-track"),progress=document.querySelector(".deck-progress i");let active=0;
function setCard(index){active=(index+cards.length)%cards.length;cards.forEach((c,i)=>c.classList.toggle("active",i===active));const step=cards[0].getBoundingClientRect().width+18;track.style.transform=`translateX(${-active*step}px)`;progress.style.width=`${(active+1)*33.33}%`;play("signal")}
document.querySelector(".next").onclick=()=>setCard(active+1);document.querySelector(".prev").onclick=()=>setCard(active-1);
cards.forEach((card,i)=>{card.addEventListener("click",e=>{if(!e.target.closest(".card-open"))setCard(i)});card.addEventListener("pointermove",e=>{const r=card.getBoundingClientRect(),device=card.querySelector(".device");if(device){device.style.setProperty("--dx",`${((e.clientX-r.left)/r.width-.5)*8}deg`);device.style.setProperty("--dy",`${((e.clientY-r.top)/r.height-.5)*-6}deg`)}})});
document.querySelector("[data-scroll]").onclick=()=>document.querySelector("#deck").scrollIntoView();
const modal=document.querySelector(".product-modal"),modalBg=document.querySelector(".modal-bg");
function openProduct(key){const p=products[key];modal.querySelector(".modal-code").textContent=p.code;modal.querySelector("h2").textContent=p.title;modal.querySelector("p").textContent=p.description;modal.querySelector("ul").innerHTML=p.features.map(x=>`<li>${x}</li>`).join("");modal.hidden=false;modalBg.hidden=false;play("signal")}
function closeModal(){modal.hidden=true;modalBg.hidden=true}
document.querySelectorAll(".card-open").forEach(b=>b.onclick=()=>openProduct(b.dataset.product));document.querySelector(".modal-close").onclick=closeModal;modalBg.onclick=closeModal;addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const object=document.querySelector(".kinetic-object"),light=document.querySelector(".pointer-light");addEventListener("pointermove",e=>{light.style.left=`${e.clientX}px`;light.style.top=`${e.clientY}px`;object.style.setProperty("--px",`${(e.clientX/innerWidth-.5)*-15}px`);object.style.setProperty("--py",`${(e.clientY/innerHeight-.5)*-10}px`)});
let context,sound=true;const soundButton=document.querySelector(".sound-control");
function unlock(e){if(e.target.closest(".sound-control"))return;context=new(window.AudioContext||window.webkitAudioContext)();document.removeEventListener("pointerdown",unlock,true)}document.addEventListener("pointerdown",unlock,true);
function play(type="tap"){if(!sound||!context)return;const now=context.currentTime,o=context.createOscillator(),g=context.createGain(),f=type==="signal"?[220,580,.16]:[260,130,.08];o.type=type==="signal"?"sine":"triangle";o.frequency.setValueAtTime(f[0],now);o.frequency.exponentialRampToValueAtTime(f[1],now+f[2]);g.gain.setValueAtTime(.035,now);g.gain.exponentialRampToValueAtTime(.0001,now+f[2]);o.connect(g).connect(context.destination);o.start();o.stop(now+f[2])}
soundButton.onclick=()=>{if(!context)context=new(window.AudioContext||window.webkitAudioContext)();sound=!sound;soundButton.setAttribute("aria-pressed",sound);soundButton.querySelector("span").textContent=sound?"Sound on":"Sound off";if(sound)play("signal")};document.querySelectorAll(".sound-target").forEach(x=>x.addEventListener("click",()=>play("tap")));
setCard(0);
